# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jérémy GFA
title: Ai and Cybersecurity Student 
email: jeremy_gfa@proton.me
website: zengdard.github.io
medium : https://medium.com/@jeremy_gfa

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  zengdard
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: jeremy-gffa
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: stendhalgpt.fr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Passionate student specializing in Artificial Intelligence and Cybersecurity, with a focus on honing skills in computer security and cyber threat management. My interests extend to digital forensics, information retrieval, and the development of semi-autonomous LLM systems.
  
  Current projects include working on a Pseudo-AGI with <mark>SFT</mark> + <mark>DPO</mark> and an auto-learning process, reflecting my enthusiasm for building innovative solutions with AI.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Aldecis
        link: aldecis.com
        # link_text: boringcompany.com
        sub_title: Assisstant Chief AI
        caption: Mai 2024 - Juillet 2024 
        quote: >
        description: | # this will include new lines to allow paragraphs
     
    content:
        - layout: left
          title: Aldecis
          link: aldecis.com
          # link_text: boringcompany.com
          sub_title: Assisstant Chief AI
          caption: Juin 2023 - Aout 2023 
          quote: >
            Transform Business Intelligence with Symbolic and Connectionist Artificial Intelligence Application.
          description: | # this will include new lines to allow paragraphs
              Revolutionize business intelligence through the integration of Symbolic and Connectionist Artificial Intelligence Application. Leverage the power of Python, including Langchain and PyTorch, along with Neo4j using Cypher query language. Implement advanced data storage and retrieval with Milvus and Pinecone. Tailor the solution specifically for the domains of Corporate Finance and Management, ensuring a comprehensive and efficient approach to business analytics and decision-making processes.
   
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Esaip
        caption: 2022 - 2025 
        sub_title: Bachelord in Cybersecurity
        quote: >
          ESAIP, the School of Responsible Futures, is a Private Institution of General Interest, accredited by the Commission des Titres d'Ingénieurs (CTI), a member of the Conference des Grandes Écoles (CGE), and part of the Federation of Institutions of Higher Education of Collective Interest (FESIC). Inspired by the lasallian tradition, ESAIP shapes tomorrow's experts in Digital Technology and Risk & Environmental Management, strategically positioned in cities like Angers, Aix-en-Provence, and Reims.
        description: | # this will include new lines to allow paragraphs
          During my time at ESAIP, I had the privilege of being immersed in the dynamic environment of the School of Responsible Futures. As the president of the 'Intelligentsia' club, which focused on economic intelligence, history, Sciences Po finance, and geopolitics, I actively organized conferences and disseminated newsletters. Additionally, I engaged in a compelling project on Symbolic AI, with guidance and support from an entrepreneurial representative. 
          
          ESAIP's strategic locations in cities like Angers, Aix-en-Provence, and Reims provided an enriching backdrop for both academic pursuits and professional collaborations.
  - title: Writting 
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some writting about Artificial Intelligence and Symbolic Approch:
      ##### - [Training a Router for a Constellation of Models in PyTorch:](https://medium.com/@jeremy_gfa/training-a-router-for-a-constellation-of-models-in-pytorch-b63fb8677535)
      ##### - [Building an Intrusion Detection System with Improved CICIDS 2017 and CSE-CICIDS 2018 Datasets using Deep Learning in Keras-TensorFlow](https://medium.com/@jeremy_gfa/building-an-intrusion-detection-system-with-improved-cicids-2017-and-cse-cicids-2018-datasets-using-95d4a66a88b6)
      ##### - [Using Encodec Meta Model in Stereo Mode with torchaudio](https://medium.com/@jeremy_gfa/using-encodec-meta-model-in-stereo-mode-with-torchaudio-7651cdc7632c)
      
      #### All can be found here :
      - [Medium](https://medium.com/@jeremy_gfa)

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: StendhalGPT
        link: stendhalgpt.fr
        # link_text: Project Website
       # additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A free ai detector.
        description: | # this will include new lines to allow paragraphs
         
         Introducing a cutting-edge ChatGPT detection system leveraging freely available N-gram models, Markov chains, and kernel distance algorithms. This innovative solution provides efficient and accessible tools for identifying instances of ChatGPT across diverse online content. Stay ahead of the curve with this open-source detector, empowering users to enhance online communication safety and security.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
